name: Publish 
on:
    push:
        branches:
            - master
            - dev
            
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Sync to Gitee 💕
              uses: wearerequired/git-mirror-action@master
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_GITEE }}
              with:
                  source-repo: "git@github.com:zhontai/Admin.Core.git"
                  destination-repo: "git@gitee.com:zhontai/Admin.Core.git"
